theme = "hyde"
languageCode = 'en-us'
title = 'Manasi Jayakumar'

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Menus]
  main = [
      {Name = "About Me", URL = "/about/", weight = 1},
      {Name = "Publications", URL = "/publications/", weight = 2},
      {Name = "Resources for grad students", URL = "/resources/", weight = 3},
  ]
  social = [
      {Name = "ai ai-cv-square ai-2x", URL = "https://drive.google.com/uc?id=1y8QUiHE5lIMbd0Y3QJa0AAu8MsrTsa1i",  weight = 1},
      {Name = "ai ai-google-scholar-square ai-2x", URL = "https://scholar.google.com/citations?user=NdH11boAAAAJ&hl=en",  weight = 2},
      {Name = "fa-brands fa-orcid fa-2x", URL = "https://orcid.org/0000-0001-5029-4922",  weight = 3},
      {Name = "fa-brands fa-github-square fa-2x", URL = "https://github.com/manasijkumar",  weight = 4},
      {Name = "fa-brands fa-twitter-square fa-2x", URL = "https://twitter.com/manasijkumar",  weight = 5},
  ]
  
[params]
  description = "Cognitive Neuroscientist"
  layoutReverse = true