theme = "hyde"
languageCode = 'en-us'
title = 'Manasi Jayakumar'

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Menus]
  main = [
      {Name = "Research", URL = "/research/", weight = 1, cards = false},
      {Name = "Teaching", URL = "/teaching/", weight = 2, cards = true},
      {Name = "Mentorship", URL = "/mentorship/", weight = 3, cards = false},
      {Name = "Resources for grad students", URL = "/resources/", weight = 4, cards = false},
  ]
  social = [
      {Name = "ai ai-cv-square ai-2x", URL = "https://drive.google.com/uc?id=1y8QUiHE5lIMbd0Y3QJa0AAu8MsrTsa1i",  weight = 1},
      {Name = "ai ai-google-scholar-square ai-2x", URL = "https://scholar.google.com/citations?user=NdH11boAAAAJ&hl=en",  weight = 2},
      {Name = "fa-brands fa-orcid fa-2x", URL = "https://orcid.org/0000-0001-5029-4922",  weight = 3},
      {Name = "ai ai-osf ai-2x", URL = "https://osf.io/4f8m5",  weight = 4},
      {Name = "fa-brands fa-github-square fa-2x", URL = "https://github.com/manasijkumar",  weight = 5},
      {Name = "fa-brands fa-twitter-square fa-2x", URL = "https://twitter.com/manasijkumar",  weight = 6},
      
  ]
  
  cards = [
      {Name = "My Teaching Experience",URL = "/teaching_exp/", weight = 1},
      {Name = "Sample Course Materials", URL = "/sample_materials/", weight = 2},
      {Name = "Teaching Effectiveness", URL = "/eff_teaching/", weight = 3},
      {Name = "Fellowships and Training", URL = "/teaching_dev/", weight = 4}
 ]
  
[params]
  description = " "
  layoutReverse = true