theme = "hyde"
languageCode = 'en-us'
title = 'Manasi Jayakumar'

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Menus]
  main = [
      {Name = "Research", URL = "/research/", weight = 1, cards = false, mentorpages = false},
      {Name = "Teaching Portfolio", URL = "/teaching/", weight = 2, cards = true, mentorpages = false},
      {Name = "Mentorship", URL = "/mentorship/", weight = 3, cards = false, mentorpages = true},
      {Name = "Resources for grad students", URL = "/resources/", weight = 4, cards = false, mentorpages = false},
  ]
  social = [
      {Name = "ai ai-cv-square ai-2x", URL = "https://drive.google.com/file/d/1y8QUiHE5lIMbd0Y3QJa0AAu8MsrTsa1i/view?usp=sharing",  weight = 1},
      {Name = "ai ai-google-scholar-square ai-2x", URL = "https://scholar.google.com/citations?user=NdH11boAAAAJ&hl=en",  weight = 2},
      {Name = "fa-brands fa-orcid fa-2x", URL = "https://orcid.org/0000-0001-5029-4922",  weight = 3},
      {Name = "ai ai-osf ai-2x", URL = "https://osf.io/4f8m5",  weight = 4},
      {Name = "fa-brands fa-github-square fa-2x", URL = "https://github.com/manasijkumar",  weight = 5},
      {Name = "fa-brands fa-twitter-square fa-2x", URL = "https://twitter.com/manasijkumar",  weight = 6},
      
  ]
  
[Params]
  description = " "
  layoutReverse = true
  cards = [
      {Name = "Teaching Statement", URL = "/teaching_statement/", weight = 1, tag = "teach"},
      {Name = "Teaching Experience", URL = "/teaching_exp/", weight = 2, tag = "teach"},
      {Name = "Sample Course Materials", URL = "/sample_materials/", weight = 3, tag = "teach"},
      {Name = "Sample Syllabus", URL = "/syllabus/", weight = 4, tag = "teach"},
      {Name = "Evidence of Effective Teaching", URL = "/effective_teaching/", weight = 5, tag = "teach"},
      {Name = "Fellowships and Development", URL = "/teaching_dev/", weight = 6, tag = "teach"},
      
      {Name = "Research Mentees", URL = "/mentees/", weight = 1, tag = "mentor"},
      {Name = "Mentor-Mentee Contract", URL = "/mentor_mentee_contract/", weight = 2, tag = "mentor"},
      {Name = "Working with me", URL = "/working_with_me/", weight = 3, tag = "mentor"}
 ]
  page_to_card_tag = [
      {Page = "Teaching Portfolio", tag="teach", class="card-columns-teach"},
      {Page = "Teaching Statement", tag="teach", class="card-columns-teach"},
      {Page = "Teaching Experience", tag="teach", class ="card-columns-teach"},
      {Page = "Sample Course Materials", tag="teach", class ="card-columns-teach"},
      {Page = "Sample Syllabus", tag="teach", class ="card-columns-teach"},
      {Page = "Evidence of Effective Teaching", tag="teach", class ="card-columns-teach"},
      {Page = "Fellowships and Development", tag="teach", class ="card-columns-teach"},
      
      {Page = "Mentorship", tag="mentor", class="card-columns-teach"},
      {Page = "Research Mentees", tag="mentor", class="card-columns-teach"},
      {Page = "Mentor-Mentee Contract", tag="mentor", class="card-columns-teach"},
      {Page = "Working with me", tag = "mentor", class="card-columns-teach"}
 ]
    