---
title: About Me
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Hello! I'm Manasi Jayakumar. 

*(Don't want to read? Listen to my interview on the Psychology PhD Podcast: available as a [Youtube video](https://www.youtube.com/watch?v=6JjnLeVy-TA){target="_blank"}, [Apple podcast](https://podcasts.apple.com/us/podcast/interview-with-manasi-jayakumar-season-2-episode-2/id1569195983?i=1000554110816){target="_blank"} or [Spotify podcast](https://open.spotify.com/episode/6cgaaLSNN5q0NDPqgBjC1H){target="_blank"} )*

I am a 4th year Ph.D. student in the Department of Psychology at Columbia University, working with Dr. Mariam Aly. Broadly my research focus is on the interaction between attention and memory, and the neural mechanisms underlying these interactions. My current research examines the relationship between spontaneous attentional fluctuations and the temporal organization of memory.


### How did I get here? ### 

I am originally from Chennai, India, but I grew up in Dubai, U.A.E. 

I graduated with an undergraduate degree in Biotechnology Engineering from Birla Institute of Technology & Science, Dubai, U.A.E. During my fourth year project, a chance encounter with  research on patient H.M. ignited my curiosity in cognitive neuroscience of memory. 

Switching careers to pursue memory research, I pursued a Master’s degree in Applied Cognition and Neuroscience at UT Dallas. During this time I worked with Dr. Michael Rugg on a cross-sectional study examining neural differences in episodic memory encoding and retrieval between young, middle-aged and older adults. 

After graduating from my master’s degree, I worked with Dr. Anthony Wagner at Stanford University as a research coordinator and lab manager. I worked on a large-scale multimodal project examining the neural mechanisms of episodic memory in healthy aging and preclinical Alzheimer’s disease.  

