---
title: Mentorship
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)

#[About page](/about/) 
# this could work to create nested pages!
```


## Mission Statement

I am committed to inclusive mentoring and mentorship practices. Over the years, I’ve had the privilege of mentoring trainees from diverse backgrounds.  Recognizing that each mentee carries their unique life experiences, skill sets, and career aspirations, I ensure a personalized approach to mentorship. At the beginning of a mentoring relationship, my mentee and I draft a <a href = "/mentor_mentee_contract/" target="_blank"> mentorship contract </a> , which explicitly outlines our shared goals and expectations. This living document is revisited and updated either at the start of each semester or every 6 months, serving as a guideline for our progress and our changing expectations. Through this structured goal- and expectation-setting, I can understand my mentee’s specific aim - whether that’s developing coding skills or exploring research design. Importantly, I place their career progression and holistic development at the forefront, blending their ambitions with my broader research objectives. By making these mutual expectations transparent, I foster an inclusive mentor-mentee dynamic but also simplify the often unspoken norms of academia. 


