---
title: Resources
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Click the arrows below to expand for resources! 

<details>
<summary><b>Programming, Statistics, and Methods</b></summary>

<h3>Programming tutorials</h3>

- [Columbia Psychology Scientific Computing](https://cu-psych-computing.github.io/cu-psych-comp-tutorial/){target="_blank"}
- [Columbia Foundations for Research Computing](https://rcfoundations.research.columbia.edu/){target="_blank"}
- [SIPPS coding workshops](https://columbia-sipps.github.io/workshops/coding_basic/){target="_blank"}
- [Data analysis and visualization for ecologists](https://github.com/mdnunez/PIPS_course){target="_blank"}
- [Programming in Psychological Sciences course](https://github.com/mdnunez/PIPS_course){target="_blank"}
- [R for data science](https://r4ds.had.co.nz/){target="_blank"}
- [Unix Shell](https://swcarpentry.github.io/shell-novice/){target="_blank"}

<h3>Git</h3>

- [Version control with Git](https://swcarpentry.github.io/git-novice/){target="_blank"}
- [Git with R studio](https://happygitwithr.com/){target="_blank"}

<h3>Statistics</h3>

- [Mixed-effects Modeling](http://mfviz.com/hierarchical-models/){target="_blank"}
- [Bayesian statistics with R](https://oliviergimenez.github.io/bayesian-stats-with-R/){target="_blank"}

<h3>Neuroimaging Analysis</h3>

- [AFNI Bootcamp](https://www.youtube.com/channel/UC40RiNZN7_dCuB6Lg7HJl1g){target="_blank"}
- [Andy’s Brain Book](https://andysbrainbook.readthedocs.io/en/latest/){target="_blank"}

<h3>Eyetracking and pupilometry</h3>

- [Basic preprocessing of pupil data](https://cran.r-project.org/web/packages/PupilPre/vignettes/PupilPre_Basic_Preprocessing.html){target="_blank"}
- Gaze R: [Github](https://github.com/dmirman/gazer){target="_blank"} | [Paper](https://link.springer.com/article/10.3758/s13428-020-01374-8){target="_blank"}| [Pre-print](https://psyarxiv.com/4qwr8){target="_blank"} | [Video tutorial](https://www.youtube.com/watch?v=EaGQD4ib5zI){target="_blank"}
- [PyGaze](http://www.pygaze.org/){target="_blank"}
- [Webgazer](https://webgazer.cs.brown.edu/#publication){target="_blank"}

<h3>Other<h3>

- [Reinforcement Learning resource guide](https://github.com/rmgeddert/Reinforcement-Learning-Resource-Guide/blob/master/RLResourceGuide.md){target="_blank"}

</details>


<details>
<summary><b>Research Skills and Tools</b></summary>

<h3>Research Skills & Tools</h3>
- [SIPPS workshops on research skills](https://columbia-sipps.github.io/workshops2021/research_skills/){target="_blank"}
- [SIPPS workshops on professional development](https://columbia-sipps.github.io/workshops2021/development/){target="_blank"}
- [Purdue OWL APA 7 guide](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/general_format.html){target="_blank"}
- [How to undertake a literature review](http://www.raulpacheco.org/2017/04/how-to-undertake-a-literature-review/){target="_blank"}
- [Connected papers](https://www.connectedpapers.com/){target="_blank"}
- [Research rabbit](https://www.researchrabbit.ai/){target="_blank"}

<h3>Other lists of lists</h3>
- [List of tools and resources for your PhD](https://github.com/helenahartmann/awesome-PhD){target="_blank"} (also links to other curated links!)
- [Free and low-cost resources](https://docs.google.com/document/d/1IFbHIN5OOAO0qz-VfCU9nEx4-x6CfArj1-d8ylA2vsU/edit){target="_blank"}
- [Aly lab’s resources](https://osf.io/mdh87/wiki/Coding%2C%20fMRI%2C%20and%20Stats%20Help/){target="_blank"}

</details>


<details>
  <summary><b>Diversity & Inclusion</b></summary>

- [A survival guide for Black, Indigeneous, and Other Women of Color in Academe](https://www.chronicle.com/article/a-survival-guide-for-black-indigenous-and-other-women-of-color-in-academe){target="_blank"}
- [Anti-Racism Resource Guide](https://www.antiracistguide.org/){target="_blank"}
- [Black Psychology and Neuroscience PIs](https://docs.google.com/spreadsheets/d/1Fbrot1qV0bqYREFYNepQiV8toT1GDDw9y7Nak_PyaZ4/edit#gid=0){target="_blank"}
- [Concrete Steps for Recruiting, Supporting, and Advancing Underrepresented Minoritized Scientists](https://docs.google.com/document/d/1Ic6bil2AvrQmPFUcUyxcw_FumofKkUo3VLsU7qG0cTk/preview?pru=AAABcsK8OBM*vB48ngj1AcbyWPbpAoY87Q){target="_blank"}
- [List of female-identifying neuroscientists](https://anneslist.net/){target="_blank"}
- [Spark Society](https://www.sparksociety.org/){target="_blank"}
- [Spark Scholars of Color Database](https://docs.google.com/spreadsheets/d/1188aq_e2FXv7qvbkrmlT3-OUT47JKU2UjY2FFt1_Y24/edit?fbclid=IwAR2TcnXFuRXAW1Iyy61drRdw9cM5vgzCM3Unb17pWXQxhJsJfblIIMwTO9w#gid=0){target="_blank"}
- South Asian Psychology and Neuroscience Association (SAPNA): [Website](https://sites.google.com/view/southasianpsychneuro/home){target="_blank"} | [Member Database](https://docs.google.com/spreadsheets/d/13Hu9Cjc_SLzqPvD8xcZEFSVT5cgkLrgzdrJOGRLh7XM/edit#gid=0){target="_blank"}

</details>


<details>
  <summary><b>Grad school and the hidden curriculum</b></summary>

<h3>Academia, grad school, and the hidden curriculum</h3>
- [PhD Stipends Database](https://www.phdstipends.com/){target="_blank"}
- Growing up in Science: [Events page](https://www.cns.nyu.edu/events/growingupinscience/){target="_blank"} | [Youtube channel](https://www.youtube.com/channel/UCgIzTiEODRtQWX6zEu_Y3fA/featured){target="_blank"}
- [Another list of resources about academia and the hidden curriculum](https://www.cns.nyu.edu/events/growingupinscience/resources.html){target="_blank"}

<h3>Advice for grad students</h3>
- [A blog post](https://dorsaamir.medium.com/modest-advice-for-new-graduate-students-b0be6b8dbc22){target="_blank"}
- [Academic Chatter](https://twitter.com/AcademicChatter){target="_blank"}
- [Academic infographics](){target="_blank"}
- [Another blog post](https://www.psychologytoday.com/us/blog/american-me-american-we/202010/things-no-one-told-me-about-pursuing-psychology-phd){target="_blank"}
- [An unofficial guidebook for PhD](https://static1.squarespace.com/static/55c143d9e4b0cb07521c6d17/t/5b4f409f575d1ff83c2f12d8/1531920545061/PhDGuidebook.pdf){target="_blank"}
- [Grad school productivity mega thread on twitter](https://twitter.com/EmanuelAviv/status/1449774083495931919){target="_blank"}
- [PhD & Productivity Youtube Channel](https://www.youtube.com/c/PhDandProductivity){target="_blank"}
- PhD Balance: [Website](https://www.phdbalance.com/){target="_blank"} | [Youtube channel](https://www.youtube.com/channel/UCI1kMS6Sm61xJAJCGqp6Pqw){target="_blank"}
- [PhD Coffee Time Youtube channel](https://www.youtube.com/c/PhDCoffeeTime){target="_blank"}
- [Productivity in PhD life](https://phdblog.jacquietran.com/2015/06/08/productivity-in-phd-life/){target="_blank"}
- [Psych Research List](https://www.psychresearchlist.com/){target="_blank"}
- [The thesis whisperer blog](https://thesiswhisperer.com/){target="_blank"}
- [Twitter thread on how to come up with ideas for research questions](https://twitter.com/ElinorHortle/status/1239308129860382720){target="_blank"}
- [What I wish I had known about doing a PhD](https://www.cns.nyu.edu/events/growingupinscience/What%20I%20wish%20I%20had%20known%20about%20doing%20a%20PhD%20-%20Q%20and%20A.pdf){target="_blank"}

<h3>Applying to grad school</h3>
- [The Psychology PhD podcast (applying to grad school)](https://psychology.columbia.edu/podcast){target="_blank"}
- [Let’s talk Gradschool](https://letstalkgradschool.substack.com/){target="_blank"}
- [How applying to grad school works](https://www.sokolhessnerlab.com/howapplyingworks){target="_blank"}
- [PhD Stipends database](https://www.phdstipends.com/){target="_blank"}
- [Twitter thread on applying to grad school as first-gen](https://twitter.com/Monica_Aswani/status/1319077412005699584){target="_blank"}
- [Project Short](https://www.project-short.com/){target="_blank"}
- [What I wish I had known about doing a PhD (20 page document)](https://www.cns.nyu.edu/events/growingupinscience/What%20I%20wish%20I%20had%20known%20about%20doing%20a%20PhD%20-%20Q%20and%20A.pdf){target="_blank"}

<h3>Fellowships</h3>
- [List of Undergraduate Summer Research Oppotunities](https://docs.google.com/spreadsheets/d/1hhrtStgv-xZqr5BESyo7HhnHAZMz_AHsxwwVO4fEd9o/edit#gid=1576403315){target="_blank"}
- [List of Graduate student fellowships](https://research.jhu.edu/rdt/funding-opportunities/graduate/){target="_blank"}
- [List of Post doc fellowships](https://research.fas.harvard.edu/postdoc_opportunities){target="_blank"}
- [Search for funding and grants for ECRs](https://ecrcentral.org/){target="_blank"}

<h3>Beyond a PhD</h3>
(I'm not there yet, so stay tuned for more resources)

- [Guide to Postdoc](https://ubadahsabbagh.com/guide-to-postdoc.php){target="_blank"}
- [Search for funding and grants for ECRs](https://ecrcentral.org/){target="_blank"}
- [My IDP](https://myidp.sciencecareers.org/?AspxAutoDetectCookieSupport=1){target="_blank"}
- [Imagine PhD](https://www.imaginephd.com/){target="_blank"}

</details>


<details><summary><b>Disabilities, Neurodiversity, & Mental Health</b></summary> 

<h3>Disabilities and Neurodiversity</h3>
- IncludeEdu: [Website](https://includedu.online/){target="_blank"} | [Twitter](https://twitter.com/IncludEduOnline){target="_blank"}
- [Diasbled in Higher Ed](https://disabledinhighered.weebly.com/dehem-2021.html){target="_blank"}
- [Job accommodation network](https://askjan.org/){target="_blank"}
- theADHDAcademic: [Website](https://theadhdacademic.weebly.com/){target="_blank"} | [Twitter](https://twitter.com/theADHDacademic){target="_blank"}
- Disabled in STEM: [Website](https://disabledinstem.wordpress.com/){target="_blank"} | [Twitter](https://twitter.com/DisabledStem){target="_blank"}

<h3>Mental Health</h3>
- [Twitter thread on how to take care of your meantal health during your PhD](https://twitter.com/ZJAyres/status/1227503028124569600){target="_blank"}
- Feeling overwhelmed by academia? You are not alone: [Nature Career Feature](https://www.nature.com/articles/d41586-018-04998-1?utm_source=twt_na&utm_medium=social&utm_campaign=NNPnature){target="_blank"} | [PDF](){target="_blank"}

</details>

<details><summary><b>For International Students</b></summary>

<h3>International student-specific resources</h3>
- [Funding opportunities for international scholars in the U.S.](https://docs.google.com/spreadsheets/d/1J7J_1hz0AjxkExUcPX24W80ZvGi71ZLS8ktUaV4bpdc/edit#gid=834995528){target="_blank"}
- [PhD Balance's international student GradChat](https://www.youtube.com/watch?v=bqPSUJnq_ik){target="_blank"}

</details>

<details><summary><b>Other</b></summary>

<h3>Fun</h3>
- [PhD Comics](http://phdcomics.com/comics.php){target="_blank"}
- [XKCD](https://xkcd.com/){target="_blank"}
- [Spurious correlations](https://www.tylervigen.com/spurious-correlations){target="_blank"}
- [Scientist on the Subway](https://scisub.com/){target="_blank"}
- [The Science Life](https://zuckermaninstitute.columbia.edu/science-life){target="_blank"}

</details>
