---
title: Sample Course Materials
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


#### Contents: 

- [Cognition: From Lab to Life!](#app_cog)
- [How To's of Research Course](#how_tos)
- [Research Methods Course](#res_med)
- [SIPPS Workshop Materials](#sipps-2023)

<center> <h2 id = "app_cog"> Cognition: From Lab to Life! </h2> </center>

The below materials are samples from my Fall 2023 seminar course titled “From lab to life: how cognition research affects everything you do!”. The 12 students in this course are sophomore, junior, and senior undergraduates. The class meets in person, on Thursdays, for 110 minutes at Columbia University. Students learn to interpret, summarize, and communicate research in cognitive psychology and neuroscience by reading assigned empirical and review papers.

### Participation Guidelines

To create an inclusive, accessible, and supportive environment, I described explicit expectations for participation and engagement in the syllabus, including 8 different styles of participation and engagement. I also created a rubric on participation and engagement that was added as an appendix to the syllabus. To encourage students to develop their metacognitive abilities by reflecting on their own performance, I had students complete two self-reflections for their participation, which I then provided feedback on. 

<center> <embed src = "/materials/Applied_Cognition_Participation_guidelines.pdf" width= 100% height= "375" type="application/pdf"> </center>


### Participation Rubric and Ungraded Self-Reflection

In addition to making expectations explicit on the syllabus, I created a rubric describing how participation and engagement would be assessed and attached this as an appendix to my syllabus. Further, to encourage students to develop their metacognitive abilities by reflecting on their own performance, I had students complete two self-reflections about their participation (Week 4 and Week 9). I then provided feedback to students so they could continue to improve their participation and engagement.

<center> <embed src = "/materials/Applied_Cognition_Participation_rubric.pdf" width= 100% height= "375" type="application/pdf"> </center>

### Guidelines for the final paper

For the course, students had to complete a final paper that was an in-depth literature review of their topic of interest. To encourage students to take ownership of their learning, students could choose the topics for their final paper, and could decide to write one of two types of papers.  To ensure student success for those from disadvantaged backgrounds or different experiences, I scaffolded the final paper so that there were three other low-stakes checkpoints for me to guide students and provide feedback (proposal, road map, and section draft). In particular, I could assess their scientific writing skills from the section draft, and provide feedback for students to produce a well-written final draft. Through these final papers, students were able to apply the knowledge and skills learned throughout the semester to their own fields of interest. 

<center> <embed src = "/materials/Applied_Cognition_Final_Paper_Guidelines.pdf" width= 100% height= "375" type="application/pdf"> </center>

---

<center> <h2 id = "how_tos"> How To's of Research Course </h2> </center>

The below materials are from the “How-To’s of Research” course that I co-taught in Spring 2023. The course enrolled 30 undergraduates who were majors (or intended to major) in psychology and/or neuroscience. We met twice a week on Tuesdays/Thursdays for 75 minutes in-person at Columbia University. This course is a research methods lecture course that gives a practical introduction to how research is conducted in psychology and neuroscience. The course provides students with a toolbox of research skills including conducting literature reviews, generating hypotheses, designing a study, and analyzing data using R. The course follows a flipped classroom setup with pre-class videos and readings, pre-class assessments, and in-class challenges. 


### Sample Pre-class Journal Prompt

Students complete journal entries as homework before coming to class. To help students develop their metacognitive abilities, the journal prompts encourage them to engage in self-reflection, learn from past mistakes, and consider how they would do things differently in the future. This particular journal prompt is focused on the impact of the previous ungraded assessment (the background/intro section) and the class discussion about open sciences practices.


<center> <embed src = "/materials/How_Tos_pre-class_journal.pdf" width= 100% height= "375" type="application/pdf"> </center>


### Sample In-class Challenge

Students complete in-class challenges in small groups for participation points. In this particular class, we covered neuroimaging methods for human research, including a brief review of EEG and fMRI. Students are then asked to dissect Fig. 6 from Tong et al., 1998.  Importantly, students are asked to discuss and interpret the findings both for a scientific audience, as well as for communicating the results to a lay audience. Through this and other such in-class challenges, students learn to think critically and independently, while practicing communication of scientific findings to varied audiences. 


<center> <embed src = "/materials/How_Tos_in-class_challenge.pdf" width= 100% height= "375" type="application/pdf"> </center>


### Guidelines for the OSF pre-registration as final project

In the How-Tos’ of Research course, students submit a final project in the form of an OSF pre-registration. Throughout the semester, this final project is scaffolded with multiple ungraded sequential assessments (text in blue in the table below). Students first chose a research topic and a general question, taking ownership of their project. Then, they submit two spreadsheets of literature reviews - one with just 5 papers, and the next with 10. This is followed by a 1-page background/introduction section. The final sub-component they submit is the methods/study design template. At each stage of this scaffolded structure, students receive both instructor and peer feedback.


<center> <embed src = "/materials/How_Tos_OSF_pre-reg_guidelines.pdf" width= 100% height= "375" type="application/pdf"> </center>


---

<center> <h2 id = "res_med"> Research Methods Course </h2> </center>

The document below depicts my feedback on students’ drafts of their research proposal from the Research Methods course that I taught in the Fall of 2021. The course was a research methods course that contained lecture classes with weekly labs and enrolled 60 undergraduates who were majors in psychology and/or neuroscience. 15 of these students were enrolled in my lab section which met once a week on Mondays for 110 minutes in-person at Columbia University. The course provided students with a toolbox of research skills including conducting literature reviews, generating hypotheses, designing a study, and analyzing data using R. 



### Sample of feedback given to students

In the Research Methods course, students propose a study or an experiment on their topic of choice for their project proposal. This project proposal was scaffolded with a series of papers that progressively built on each other: a literature review, the methods section, and a draft of the project proposal (excerpts below), before they submitted a final project proposal. At each stage of this scaffolded structure, students received timely feedback from me. Given below are examples of my feedback for two different students on the introduction of their proposal draft. To ensure that every student incorporated my feedback, I began each class by reviewing the common mistakes, suggesting ways to improve on them, and emphasizing the importance of integrating feedback from previous drafts. 


<center> <embed src = "/materials/.pdf" width= 100% height= "375" type="application/pdf"> </center>

---

<center> <h2 id = "sipps-2023"> SIPPS Workshop Materials </h2> </center>



Below, you can find materials from my SIPPS workshops in 2023. We adapted our SIPPS curriculum to a flipped classroom approach: students watched short pre-workshop videos and engaged in hands-on activities during the workshop sessions. 


### Research Skills

- How to read a paper:
    - Pre-workshop materials: [video](https://youtu.be/XKrSwonwLL0){target="_blank"} | [slides](/materials/sipps/AcademicPaper-pre-workshop_slides.pdf){target="_blank"} | [Lit Review Table](/materials/sipps/AcademicPaper-LitReview_Table.xlsx){target="_blank"} | [QualMRI Handout](/materials/sipps/AcademicPaper-QuALMRI_Handout.pdf){target="_blank"} | [QualMRI Template](/materials/sipps/AcademicPaper-QuALMRI_Template.docx){target="_blank"}
    - Synchronous Workshop materials: [slides](/materials/sipps/AcademicPaper-sync_workshop_slides.pdf){target="_blank"} | [Paper 1](/materials/sipps/AcademicPaper-ChapmanColbyLi2014.pdf){target="_blank"} | [Paper 2](/materials/sipps/AcademicPaper-Godden1975.pdf){target="_blank"}


- Research Ethics:
    - Pre-workshop materials: [video](https://youtu.be/b1WcZ6G9Uls){target="_blank"} | [slides](/materials/sipps/ResearchEthics-pre-workshop_slides.pdf){target="_blank"}
    - Synchronous Workshop materials: [slides](/materials/sipps/ResearchEthics-sync_workshop_slides.pdf){target="_blank"} | [IRB Response Sheet](/materials/sipps/ResearchEthics-IRBResponseSheet.docx){target="_blank"} | [Application Under Review](/materials/sipps/ResearchEthics-application_under_review.pdf){target="_blank"} | [Approved Application for reference](/materials/sipps/ResearchEthics-approved-application.pdf){target="_blank"}

### Professional Development 

- CVs and Resumes:
    - Pre-workshop materials: [video](https://youtu.be/anRwuA0RIac){target="_blank"} | [slides](/materials/sipps/CVResume-slides.pdf){target="_blank"}
    - Synchronous Workshop materials: [CV - SIPPS template](/materials/sipps/CV_template_SIPPS.docx){target="_blank"}

### R programming

- Introduction to Linear Models:
    - Pre-workshop materials: [Overview of linear regression video](https://youtu.be/_uR9RcC2t5U){target="_blank"} | [slides](/materials/sipps/IntroLM-workshop_slides.pdf){target="_blank"} | [Linear Regression R tutorial video](https://youtu.be/M5ejllMuNKw){target="_blank"} |  [RMarkdown Lesson File](/materials/sipps/IntroLM-lesson.Rmd){target="_blank"} | [RMarkdown Lesson with Key](/materials/sipps/IntroLM-lesson-key.Rmd){target="_blank"} | [R Project file](/materials/sipps/IntroLM.Rproj){target="_blank"}



---

