---
title: Fellowships, Awards, and Teaching Development
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

#### Contents: 

- [Teaching Fellowships](#teach-fellowships)
- [Awards](#teach-awards)
- [Pedagogical Development](#teach-dev)

<center><h2 id = "teach-fellowships"> Fellowships </h2></center>


<h3><a href="https://www.gsas.columbia.edu/content/gsas-teaching-scholars-program" target = "_blank">Teaching Scholar, Graduate School of Arts and Sciences, Columbia University</a></h3>
**2023-2024**

- Appointed by the Dean of GSAS granting me an opportunity to teach a course in the academic year (<a href= "https://www.gsas.columbia.edu/content/teaching-scholars" target = "_blank">less than 25 scholars are appointed every year</a>)
- Only student nominated by the Department of Psychology for this academic year based on my record as a researcher and future promise as an educator
- Designed a seminar course titled “From lab to life: How cognition research affects everything you do!” from scratch that combines my interests and expertise while addressing the needs of the department 
- Appointed as the Instructor of Record for this seminar course in Fall 2023
- Fellowship covers sixth year funding (stipend, tuition, and fees)

<h3><a href= "https://ctl.columbia.edu/graduate-instructors/opportunities-for-graduate-students/teaching-assessment-fellows/" target = "_blank">Teaching Assessment Fellow, Center for Teaching and Learning, Columbia University</a></h3>
**2023-2024**

- Applied and awarded fellowship for the academic year
- Partner with faculty on projects funded through the Provost’s office to assist with assessing the effectiveness of Teaching as Research projects.


<h3><a href= "https://ctl.columbia.edu/graduate-instructors/opportunities-for-graduate-students/lead-teaching-fellows/" target = "_blank">Lead Teaching Fellow, Center for Teaching and Learning, Columbia University</a></h3>
**2022-2023**

- Applied and awarded fellowship for the academic year
- Organized a workshop for the Psychology department's graduate students and post-docs titled “Agency as a TA: Building relationships with our students and creating inclusive learning environments” 
- Acted as liaison between psychology PhD students and the Center for Teaching and Learning 
- Developed a resource for teaching and TA'ing within the department
- Conducted a needs assessment within the department, and organized a department-specific micro-teaching session.

---

<center><h2 id = "teach-awards"> Awards </h2></center>

**2023** <a href="https://teachpsych.org/gradtravel" target = "_blank"> Graduate Student Travel Grant </a> for Society for the Teaching of Psychology's <a href="https://teachpsych.org/conferences/act.php/" target = "_blank">Annual Conference on Teaching</a> 



---

<center><h2 id = "teach-dev"> Pedagogical Development </h2></center>


### Teaching Development Program - Advanced Track

In addition to the required pedagogy seminar in the department of psychology, I pursued and completed the advanced track of the Teaching Developement Program offered by the Center for Teaching and Learning. This involved actively engaging in 12 workshops, completing a multi-session intensive seminar, completing observations (both of myself, and other instructors), and creating a robust teaching portfolio.

### List of  Workshops attended 
*(led or overseen by the Center for Teaching and Learning at Columbia University)*

- Essentials of Teaching and Learning (4-part series)
- Illuminating the learning process
- Reflections on a year and a half of online teaching and learning (2-part series)
- Ungrading and Re-centering Process in the Classroom
- Difficult Knowledge and Inclusive 
- Teaching by Observing: Effective teaching observations
- Teaching through Discussion
- Careers in Educational Development
- Assessing Teaching and Learning

### Intensive Seminar on Inclusive Teaching

- Completed a 5-part intensive series by reflecting on my current inclusive teaching experiences and practices,  engaging with scholarship on inclusive teaching, and applying it to my teaching practice. 
- Authored my “Statement of Inclusive Teaching”, which explicitly documents my  commitment to creating an inclusive environment and is directed at students. I incorporated this statement into my syllabus for the applied cognition research seminar I teach as the Teaching Scholar. 


---

