---
title: Teaching Portfolio
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

<center><h2>Mission Statement</h2></center>


In this age of easy access to misinformation, scientific literacy is essential for students to understand the world and to critically evaluate and validate any information they are presented with. **My mission as an educator is to prepare students to be independent and critical thinkers, who are scientifically literate and able to apply their knowledge to their fields of interest.**

To accomplish this, I create an **inclusive and supportive learning environment** by making expectations as explicit as possible, which allows students to push their boundaries and explore their interests. 

Additionally, **as an attention and memory researcher, I integrate the science of learning with my teaching.** I encourage students to take ownership of their progress and learn from their mistakes instead of viewing them as failures. I scaffold major assignments with smaller low-stakes sub-components that build on each other so students have the opportunity to push their boundaries, make mistakes, and learn from them. I encourage students to generate solutions to problems, without giving them the solution outright. This builds their confidence and helps them remember the solutions better for the future. 

---


To see a more detailed version of my teaching philosophy, please see my teaching statement <a href=/teaching_statement/>here </a>.

To see what my students have to say about my teaching, please see <a href=/eff_teaching/>a summary of my teaching evaluations here </a>. 

I also have <a href = /sample_materials/> annotated samples of my course materials here </a>, and <a href = /syllabus/> a sample syllabus </a> on this webpage. Please don’t hesitate to reach out if you have any questions or would like to borrow any of my materials! 


---
